version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7
    container_name: dundra-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: dundra
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - dundra-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    container_name: dundra-backend
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: mongodb://admin:password123@mongodb:27017/dundra?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-for-development
      CORS_ORIGIN: http://localhost:5173
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - mongodb
    networks:
      - dundra-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React app
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: development
    container_name: dundra-frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    environment:
      VITE_API_URL: http://localhost:5000
      VITE_SOCKET_URL: http://localhost:5000
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    networks:
      - dundra-network

  # Redis for session storage (optional)
  redis:
    image: redis:7-alpine
    container_name: dundra-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - dundra-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  dundra-network:
    driver: bridge
